### ISSUE TITLE
修剪器执行后给value赋值,value值没变

### ISSUE THREAD

**Issue by wx11055** [dxvgef/filter#5]
validation.go:15 
value修建后跟之前的value一样.

**Comment by dxvgef** [comment]
原本计划`filter.Result()`只做验证用途，修剪器也只为了验证用，并不返回修剪后的结果。
已经为`filter.Result()`函数增加了一个出参，就是修剪后的值。

**Comment by dxvgef** [comment]
v1.0.0及之后的版本已经重新调整了结构，没有这个问题了
